[package]
name = "bib-picker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biblatex = "0.6.3"
itertools = "0.10.5"
skim = "0.10.2"
tui = "0.19.0"
